import type { Vehicle } from "../types";

export const VEHICLE_IMAGES = {
  "hero-bmw": require("../assets/figma/home/hero-bmw.png"),
  "mercedes-e350": require("../assets/figma/cars/mercedes-e350.png"),
  "porsche-cayenne": require("../assets/figma/cars/porsche-cayenne.png"),
  "tesla-model-s": require("../assets/figma/cars/tesla-model-s.png"),
  "audi-a8": require("../assets/figma/cars/audi-a8.png"),
  "lexus-es": require("../assets/figma/cars/lexus-es.png"),
  "bmw-x3": require("../assets/figma/cars/bmw-x3.png"),
  "audi-a6": require("../assets/figma/cars/audi-a6.png"),
  "range-rover": require("../assets/figma/cars/range-rover.png"),
} as const;

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "bmw-x5",
    nameKey: "bmw-x5",
    brand: "BMW",
    model: "X5",
    year: 2025,
    pricePerDay: 450,
    rating: 4.9,
    category: "suv",
    image: "hero-bmw",
    imageSource: VEHICLE_IMAGES["hero-bmw"],
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    featured: true,
  },
  {
    id: "mercedes-e350",
    nameKey: "mercedes-e350",
    brand: "Mercedes-Benz",
    model: "E350",
    pricePerDay: 600,
    rating: 4.9,
    category: "luxury",
    image: "mercedes-e350",
    imageSource: VEHICLE_IMAGES["mercedes-e350"],
    locationKey: "khobar",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    featured: false,
  },
  {
    id: "porsche-cayenne",
    nameKey: "porsche-cayenne",
    brand: "Porsche",
    model: "Cayenne",
    pricePerDay: 900,
    rating: 4.8,
    category: "sport",
    image: "porsche-cayenne",
    imageSource: VEHICLE_IMAGES["porsche-cayenne"],
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: false,
    featured: false,
  },
  {
    id: "tesla-model-s",
    nameKey: "tesla-model-s",
    brand: "Tesla",
    model: "Model S",
    pricePerDay: 550,
    rating: 4.7,
    category: "electric",
    image: "tesla-model-s",
    imageSource: VEHICLE_IMAGES["tesla-model-s"],
    locationKey: "dammam",
    seats: 5,
    transmission: "automatic",
    fuelType: "electric",
    instantBook: true,
    featured: false,
  },
  {
    id: "audi-a8",
    nameKey: "audi-a8",
    brand: "Audi",
    model: "A8",
    pricePerDay: 800,
    rating: 4.9,
    category: "luxury",
    image: "audi-a8",
    imageSource: VEHICLE_IMAGES["audi-a8"],
    locationKey: "dammam",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    featured: false,
  },
  {
    id: "lexus-es",
    nameKey: "lexus-es",
    brand: "Lexus",
    model: "ES",
    year: 2025,
    pricePerDay: 550,
    rating: 4.8,
    category: "luxury",
    image: "lexus-es",
    imageSource: VEHICLE_IMAGES["lexus-es"],
    locationKey: "riyadh",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    favorite: true,
    featured: false,
  },
  {
    id: "bmw-x3",
    nameKey: "bmw-x3",
    brand: "BMW",
    model: "X3",
    pricePerDay: 680,
    rating: 4.8,
    category: "suv",
    image: "bmw-x3",
    imageSource: VEHICLE_IMAGES["bmw-x3"],
    locationKey: "dammam",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    favorite: true,
    featured: false,
  },
  {
    id: "audi-a6",
    nameKey: "audi-a6",
    brand: "Audi",
    model: "A6",
    pricePerDay: 600,
    rating: 4.7,
    category: "luxury",
    image: "audi-a6",
    imageSource: VEHICLE_IMAGES["audi-a6"],
    locationKey: "riyadh",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: false,
    favorite: true,
    featured: false,
  },
  {
    id: "range-rover-velar",
    nameKey: "range-rover-velar",
    brand: "Range Rover",
    model: "Velar",
    pricePerDay: 950,
    rating: 4.9,
    category: "suv",
    image: "range-rover",
    imageSource: VEHICLE_IMAGES["range-rover"],
    locationKey: "jeddah",
    seats: 5,
    transmission: "automatic",
    fuelType: "petrol",
    instantBook: true,
    favorite: true,
    featured: false,
  },
];

export const FEATURED_VEHICLE = MOCK_VEHICLES.find((v) => v.id === "bmw-x5")!;
export const EXPLORE_VEHICLES = MOCK_VEHICLES.filter((v) =>
  ["mercedes-e350", "porsche-cayenne", "tesla-model-s", "audi-a8"].includes(v.id),
);
export const FAVORITE_VEHICLES = MOCK_VEHICLES.filter((v) => v.favorite);

export function getVehicleById(id: string): Vehicle | undefined {
  return MOCK_VEHICLES.find((v) => v.id === id);
}
